core_variables:
  - pais
  - anio
  - trimestre
  - id
  - ponderador
  - sexo
  - edad
  - nivel_educativo
  - educacion_superior

  - ocupado
  - desocupado
  - inactivo

  - asalariado
  - asalariado_publico
  - asalariado_privado
  - cuentapropia
  - patron
  - trab_familiar
  - empleo_domestico

  - formal
  - informal
  - small
  - patron_micro
  - asalariado_privado_micro

  - sector

rules:
  ocupado:
    definition: "criterio armonizado tipo EPH"

  informal:
    definition: "criterio híbrido basado en argentina_estructura"

  ponderador:
    rule: "usar sin modificar en todos los países"
